server:
  port: ****
spring:
  application:
    name: FARM-MANAGEMENT-SERVICE
  data:
    mongodb:
      uri: mongodb://*****/
      database: agriculture_db
      auto-index-creation: true
      
  threads:
    virtual:
      enabled: true
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://******/eureka 