# -*- coding: utf-8 -*-
"""download.ipynb

Automatically generated by Colab.

"""

#!pip install timm

import timm
from fastai.vision.all import *
from io import BytesIO
from PIL import Image
import pickle
from huggingface_hub import from_pretrained_fastai, _save_pretrained_fastai
from contextlib import contextmanager
from pathlib import Path
import pathlib

tomato = from_pretrained_fastai("Luna-Skywalker/tomato_dtect")

_save_pretrained_fastai(tomato, "./ml_models/tomato_dtect")